name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos:
    runs-on: macos-10.15

    strategy:
      matrix:
        xcode:
          - "12.4" # Swift 5.3

    name: "macOS Catalina (Xcode ${{ matrix.xcode }})"

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-xcode-${{ matrix.xcode }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-xcode-${{ matrix.xcode }}-
      - name: Build and Test
        run: |
          swift test
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
